kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    course: devops
    trainer: sivakumar
  annotations:
    kubernates.io/created-by: ramu
    jenkins.build.url: 'https://jenkins.daws78s.online/expense/job/backend/54'  
spec:
  containers:
  - name: nginx
    image: nginx    